name: Add release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag for the release (usually YYYYMMDD, but any unique string)
        required: true
      date:
        description: The date of the release (YYYY-MM-DD)
        required: true
      description:
        description: The description of the release, what was fixed / added?
        required: true

jobs:
  add-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          persist-credentials: true

      - name: Append JSON data
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs').promises;
            const data = { date: context.payload.inputs.date, tag: context.payload.inputs.tag, description: context.payload.inputs.description };
            const jsonData = JSON.stringify(data) + '\n';
            await fs.appendFile('src/releases.ndjson', jsonData);

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '<>'
          git add src/releases.ndjson
          git commit -m "(GITHUB ACTION) add release"
          git push origin main

      - name: Trigger pull action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          curl -X POST \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: Bearer ${GITHUB_TOKEN}' \
          -H 'Content-Type: application/json' \
          -d '{"event_type":"push","client_payload":{"ref":"refs/heads/main"}}'
