name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: The tag for the release (usually YYYYMMDD, but any unique string)
        required: true
      date:
        description: The date of the release (YYYY-MM-DD)
        required: true
      description:
        description: The description of the release, what was fixed / added?
        required: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  add-release:
    runs-on: ubuntu-latest
    if: (github.event_name == 'workflow_dispatch')
    outputs:
      ref: ${{ steps.commit_and_push.outputs.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          persist-credentials: true

      - name: Append JSON data
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs').promises;
            const data = { date: context.payload.inputs.date, tag: context.payload.inputs.tag, description: context.payload.inputs.description };
            const jsonData = JSON.stringify(data) + '\n';
            await fs.appendFile('src/releases.ndjson', jsonData);

      - name: Commit and push changes
        id: commit_and_push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '<>'
          git add src/releases.ndjson
          git commit -m "(GITHUB ACTION) add release"
          git push origin main
          echo "ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: add-release
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # If we added a release, we want to check out the new ref, otherwise the default is fine:
          ref: ${{ needs.add-release.outputs.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && always()

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
